### ISSUE TITLE
batchtools config always overrides default.resources

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#208]
I think the change from the configRMINCparallel("sge") to the option method has triggered a bit of a bug.

Since I set a config file option, this file *always* takes presidence over my environment in the cluster run, preventing me from changing default.resources except by changing the file (or pointing at a new one).

This is probably not working as intended

**Comment by cfhammill** [comment]
are you using `mincLmer` by any chance or does this apply to more functions? I'm aware of a bug in `mincLmer` where the `conf_file` argument get overwritten by `getOption("RMINC_BATCH_CONF")`. If this is the one that is biting you, you can set this option with `option(RMINC_BATCH_CONF = my_file)`. https://github.com/Mouse-Imaging-Centre/RMINC/blob/master/R/minc_lmer.R#L177

There is another small issue in the default config files, they reference `vmem`, but it should be `memory`
https://github.com/Mouse-Imaging-Centre/RMINC/blob/master/inst/parallel/sge_batchtools.R#L4

I'll push these fixes to develop tomorrow.

**Comment by gdevenyi** [comment]
Im using mincLmer.

To be clear, the bug is that the config file is overriding an environment with the default.ressources set.

The current design means I can only set things via a config file.

**Comment by cfhammill** [comment]
Ah I see, the API has changed slightly, all configuration is done through the `resources` argument to `pMincApply` or `qMincApply`. Or with a config file. Having a configuration list in local scope shouldn't do anything. So I think this points to a few things, I need to add the resources argument to `mincLmer` and other parallel functions that aren't `p/qMincApply` if they aren't there already, and update the parallel docs to reflect the changes.

**Comment by gdevenyi** [comment]
Ah okay, this change makes more sense than the previously configuration in the environment.

Can I pass resources into mincLmer right now or does it need some changes to pass it forward properly?

**Comment by cfhammill** [comment]
Presently it doesn't take a `resources` argument, and unfortunately as noted above the `conf_file` argument is currently ignored. I'll issue a small release with fixes in the next week or two. For now you will need to write your desired configuration list to a file.

e.g. 

```
cluster.functions <- makeClusterFunctionsSGE(system.file("parallel/sge_script.tmpl", package = "RMINC"))
default.resources <-
  list(nodes = 1,
       memory = "12G",
       walltime = "08:00:00")
```

save this as "my_conf.R" or whatever

Then use 

```
old_conf <- options("RMINC_BATCH_CONF")
options(RMINC_BATCH_CONF = "my_conf.R")
mincLmer(.....)

options(RMINC_BATCH_CONF = old_conf)
```

Sorry for the inconvenience

**Comment by gdevenyi** [comment]
kk, will go with the file for now, thanks.

**Comment by cfhammill** [comment]
Should be fixed.

**Comment by gdevenyi** [comment]
Still broken for specified ``resources = `` on the mincLmer call.
